name: better_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_linkify: ^6.0.0
  flutter_markdown: ^0.6.9+1
  flutter_svg: ^2.0.9
  get: 4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  intl: ^0.19.0
  simple_markdown_editor: ^0.2.0
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/svg/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/fill_logo.png"
  min_sdk_android: 21 